version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tg-channel-to-rss"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-epznwwfligo2"
s3_prefix = "tg-channel-to-rss"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
image_repositories = []
disable_rollback = false
parameter_overrides = "ApiKey="
